### ISSUE TITLE
How did you exclude the dataset? Can you provide the dataset?

### ISSUE THREAD

**Issue by ZaiyiHu** [NJU-LHRS/OME#1]
Hi! Excellent Work! Saw it from Wechat.
I'm very insterested in you work. However, I'm confused about the filtered dataset, it seems quite important for the training process, but I haven't get it that how did you exclude the dataset. Quoted from the paper that 1) "The patches for training the classification network are filtered by removing the samples with pixels of any category smaller than 10% (2.5% for the small object of car) of the total pixels." 2) "Hence, we exclude samples with a small number of pixels for certain category to train the classification network."
How did you exclude the dataset? Can you provide the dataset? Thanks!

**Comment by LZhenShi** [comment]
Hi! Thanks for your attention to our work!
The dataset filtering aims at removing the images which only possess scarse pixels for certain category. 
Different patch sizes can lead to different datasets. So I have added the data processing codes, for the convenience of customizing your own dataset.
Hope this can help you!
